# Site settings
title: 유지수 | Python Developer
description: Python Developer passionate about software development and AI
author: 유지수
email: 7slwm7@naver.com

# Build settings
markdown: kramdown
# theme: minima  # 커스텀 CSS 사용으로 비활성화

# Social links
github_username: master0419
linkedin_username: jsyoo-linkedin

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
